[build]
  command = "npm run build"
  functions = "lambda" #  netlify-lambda reads this

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "chrome-aws-lambda",
    "puppeteer-core"
  ]